### ISSUE TITLE
Problems on Mac OSX in starting soapy with GUI

### ISSUE THREAD

**Issue by stefanocovino** [AOtools/soapy#70]
Hello,

I have installed soapy both under python2.7 and python 3.5 through the specific anaconda distributions. Indeed the proposed test runs fine in both cases. 
However, as soon as I try to start soapy with the GUI I have errors in both environments.

For python2.7:

soapy -g conf/sh_8x8.yaml
Traceback (most recent call last):
  File "/Users/covino/anaconda/bin/soapy", line 12, in <module>
    from soapy import gui
  File "/Users/covino/anaconda/lib/python2.7/site-packages/soapy/gui.py", line 52, in <module>
    from . import pyqtgraph
  File "/Users/covino/anaconda/lib/python2.7/site-packages/soapy/pyqtgraph/__init__.py", line 30, in <module>
    from . import python2_3
ImportError: cannot import name python2_3

and for python3.5:

soapy -g conf/sh_8x8.yaml
Traceback (most recent call last):
  File "/Users/covino/owncloud/Pacchetti/anaconda3/bin/soapy", line 12, in <module>
    from soapy import gui
  File "/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/soapy/gui.py", line 52, in <module>
    from . import pyqtgraph
  File "/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/soapy/pyqtgraph/__init__.py", line 204, in <module>
    from .graphicsItems.VTickGroup import * 
ImportError: No module named 'soapy.pyqtgraph.graphicsItems'

Is there anything I can do?

Bye,
  Stefano

**Comment by andrewpaulreeves** [comment]
Hi Stefano, 

Hmmm....I'm not quite sure why it would be doing this, I also use the anaconda distribution on my Mac and it seems to work ok. I'm off work until Tuesday after Easter but will do a little digging then. Hopefully its just that pyqtgraph needs an update or something similar.

Cheers,

Andrew

**Comment by andrewpaulreeves** [comment]
This bug was due to not including all packages in the setup.py description - the installation now uses setuptools which can install all packages. 
This should be fixed if you update and reinstall version 0.13.1
