### ISSUE TITLE
GUI not launching

### ISSUE THREAD

**Issue by RustanaBladon** [AOtools/soapy#77]
When I attempt to run soapy in GUI mode (as per the docs), I get the following error:

D:\Anaconda2\lib\site-packages\IPython\qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
Traceback (most recent call last):
  File "soapy", line 12, in <module>
    from soapy import gui
  File "D:\Anaconda2\lib\site-packages\soapy-0.13.1-py2.7.egg\soapy\gui.py", line 40, in <module>
    from IPython.qt.console.rich_ipython_widget import RichIPythonWidget
ImportError: No module named rich_ipython_widget

Any ideas on a work around?
Thanks

**Comment by andrewpaulreeves** [comment]
Hi @RustanaBladon !

It seems to be something to do with the ipython qtconsole, which is now spun off into its own package, "qtconsole" under the Jupyter umbrella. Soapy tries to use the new Jupyter conventions and falls back to the old IPython packages if it can't use them, it seems that it can't find either in your installation! This is odd, as usually Anaconda python comes packaged with jupyter included.

I've had a go at reproducing the error using the latest version (4.4.0) of Anaconda2 on Windows, everything seems to work fine without installing any extra packages. Perhaps you could try updating your Anaconda python distribution?

Andrew

(note - for performance purposes you're best to also install [pyfftw](https://github.com/pyFFTW/pyFFTW), this will be a requirement for the next Soapy version)
